#cloud-config

package_update: true
package_upgrade: true

packages:
  - liblttng-ust0
  - libkrb5-3
  - zlib1g
  - libssl1.1
  - libicu63
  - curl
  - unzip

users:
  - name: builder
    groups: wheel
    primary_group: builder
    sudo: ALL=(ALL) NOPASSWD:ALL

runcmd:
  - - su
    - builder
    - bash
    - -c
    - |
      mkdir /home/builder/actions-runner
      cd /home/builder/actions-runner
      curl -L https://github.com/actions/runner/releases/download/v2.278.0/actions-runner-linux-x64-2.278.0.tar.gz -o runner.tar.gz
      tar xzf runner.tar.gz
      env ./config.sh --unattended --url https://github.com/drogue-iot/drogue-cloud-testing --labels hetzner,@@RUNNER@@ --replace --token @@TOKEN@@

  - - bash
    - -c
    - |
      cd /home/builder/actions-runner
      ./svc.sh install builder
      ./svc.sh start
