#cloud-config

package_upgrade: true

packages:
  - lttng-ust
  - openssl-libs
  - krb5-libs
  - zlib
  - libicu
  - glibc-devel
  - firefox
  - curl
  - unzip
  - jq

users:
  - name: builder
    groups: wheel
    primary_group: builder
    sudo: ALL=(ALL) NOPASSWD:ALL

runcmd:
  - - su
    - builder
    - bash
    - -c
    - |
      mkdir /home/builder/actions-runner
      cd /home/builder/actions-runner
      curl -L @@RUNNER_URL@@ -o runner.tar.gz
      tar xzf runner.tar.gz
      env ./config.sh --unattended --url https://github.com/drogue-iot/drogue-cloud-testing --labels hetzner,@@RUNNER@@ --replace --token @@TOKEN@@

  - - bash
    - -c
    - |
      cd /home/builder/actions-runner
      ./svc.sh install builder
      ./svc.sh start
