
title: Drogue IoT Cloud test results
description: |
  This page hosts test results for Drogue IoT Cloud test runs.

twitter_username: DrogueIoT
github_username: drogue-iot

domain: drogue-iot.github.io
url: https://drogue-iot.github.io
baseurl: /drogue-cloud-testing
encoding: utf-8

theme: minima

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

minima:
  social_links:
    twitter: DrogueIoT
    github: drogue-iot
