[package]
name = "drogue-cloud-tests"
version = "0.5.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.8"
anyhow = "1"

maplit = "1"

url = { version = "2", features = ["serde"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
serde = "1"
serde_json = "1"

async-trait = "0.1"
test-context = "0.1"
rstest = "0.10"

rstest_reuse = "0.1.3"
async-std = "1"

futures = "0.3"
#lazy_static = "1"
#async_once = "0.2"

fantoccini = "0.17.4"
#webdriver-install = "0.3.2"

base64 = "0.13"
uuid = { version = "0.8", features = ["v4"] }

tokio = { version = "1.7", features = ["full", "rt-multi-thread"] }

paho-mqtt = { version = "0.9", features = ["bundled"] }

[patch.crates-io]
#fantoccini = { path = "../fantoccini" }
