name: System Test
on:
  workflow_dispatch:
    inputs:
      releaseUrl:
        description: The URL to the release file
        required: true

jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04

    env:
      CLUSTER: "kind"

    steps:

      - uses: actions/checkout@v2

      - name: Install drg
        run: |
          mkdir -p "$HOME/.local/bin"
          curl -sL https://github.com/drogue-iot/drg/releases/download/v0.5.1/drg-0.5.1-linux-amd64.tar.gz -o drg.tar.gz
          tar --strip-components=1 -xvzf drg.tar.gz
          mv drg "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Download release
        run: |
          mkdir release
          cd release
          curl -sL "${{ github.event.inputs.releaseUrl }}" -o release.zip
          unzip release.zip
          mv drogue-install-*/* .
          find .

      - name: Check for installer script
        run: |
          cd release
          test -f ./scripts/drogue.sh

      - name: Create Kind cluster
        uses: helm/kind-action@v1.1.0
        with:
          wait: 300s
          cluster_name: kind

      - name: Deploy Drogue
        run: |
          cd release
          ./scripts/drogue.sh
        timeout-minutes: 20

      - name: Run tests
        run: |
          make
